# Generated by Django 5.2.17 on 2026-09-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0003_labourentry_labour_entry_amounts_are_valid'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='labourentry',
            name='labour_entry_amounts_are_valid',
        ),
        migrations.RemoveField(
            model_name='labourentry',
            name='paid_amount',
        ),
        migrations.AddConstraint(
            model_name='labourentry',
            constraint=models.CheckConstraint(condition=models.Q(('wage__gte', 0)), name='labour_entry_wage_is_valid'),
        ),
        migrations.AddField(
            model_name='labourpayment',
            name='labour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='labour.labour'),
        ),
        migrations.AddField(
            model_name='labourpayment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_payments', to='sites.site'),
        ),
        migrations.AddConstraint(
            model_name='labourpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='labour_payment_amount_positive'),
        ),
    ]
