# Generated by Django 5.2.17 on 2026-09-12 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0004_labourpayment_and_more'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_records', to='sites.site')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('site', 'date'), name='unique_daily_site_work')],
            },
        ),
    ]
